config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  post "/session/create" => "session#create"
  post "/email/create" => "email#create"
  post "/email/draft" => "email#draft"
  get "/first_sign_in" => "welcome#first_sign_in"
  post "/save_password" => "session#save_password"
  get "/mail_box" => "mailbox#index"
  get "/mail_box_sent" => "mailbox#sent"
  get "/mail_box_delete" => "mailbox#delete"
  get "/mail_box_draft" => "mailbox#draft"

  mount ActionCable.server => '/cable'
  resources :email
  get "/all_mail_users" => "email#all_users_for_email"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
end

app/models/email.rb
class Email < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader 
  
  after_create_commit { EmailsBroadcastJob.perform_later(self) }
  belongs_to :sender, class_name: "User", primary_key: "id"
  belongs_to :recipient, class_name: "User", primary_key: "id"

  # belongs_to :cc, class_name: "User", primary_key: "cc"
  # belongs_to :bcc, class_name: "User", primary_key: "bcc"
end

app/models/user.rb
class User < ActiveRecord::Base

  include BCrypt
  belongs_to :company
  has_many :sent_emails, class_name: "Email", foreign_key: "sender_id"
  has_many :received_emails, class_name: "Email", foreign_key: "recipient_id"
  # has_many :cc_emails, class_name: "Email", foreign_key: "cc"
  # has_many :bcc_emails, class_name: "Email", foreign_key: "bcc"

  before_save :create_hashed_password, if: :password_changed?
  validates_length_of :password, minimum: 6, if: :password_changed?

  def create_hashed_password
    if password
      self.password = Password.create(password)
    end
  end

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
  protect_from_forgery with: :exception

 helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController

  def all_users_for_email
    curren_company = current_user.company.id
    # all_users = User.where(company_id: curren_company)
    render json: User.where(company_id: curren_company).to_json()
  end

  def create
    begin
      @email = Email.new(
        sender_id: params[:sender_id],
        recipient_id: params[:recipient_id],
        body: params[:body],
        subject: params[:subject],
        state: 1,
        cc: params[:cc],
        bcc: params[:bcc],
        attachment: params[:attachment],
        read: false
      )
      respond_to do |format|
        if @email.save
          format.json { render json: @email.to_json() }
        else
          format.json { render json: @email.errors.full_messages, status: :unprocessable_entity }
        end
      end
    rescue => error
      Rails.logger.error error
      respond_to do |format|
        format.json { render json: error.message, status: :unprocessable_entity }
      end
    end
  end

  def draft
    begin
      @email = Email.new(
        sender_id: params[:sender_id],
        recipient_id: params[:recipient_id],
        body: params[:body],
        subject: params[:subject],
        state: params[:state],
        cc: params[:cc],
        bcc: params[:bcc],
        attachment: params[:attachment]
      )
      respond_to do |format|
        if @email.save
          format.json { render json: @email.to_json() }
        else
          format.json { render json: @email.errors.full_messages, status: :unprocessable_entity }
        end
      end
    rescue => error
      Rails.logger.error error
      respond_to do |format|
        format.json { render json: error.message, status: :unprocessable_entity }
      end
    end
  end
  def show
    @email = Email.find(params[:id])
    @email.update(read: true)
    @current_company = current_user.company_id
    # all_users = User.where(company_id: curren_company)
    @email_users = User.where(company_id: @current_company).to_json()
  end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController

  def index
    @emails = Email.where(state: 1, recipient_id: current_user.id).order( "created_at DESC")
    @current_company = current_user.company_id
    # all_users = User.where(company_id: curren_company)
    @email_users = User.where(company_id: @current_company).to_json()
  end

  def sent
    @emails = Email.where(sender_id: current_user.id).order( "created_at DESC")
    curren_company = current_user.company_id
  end

  def delete
    @emails = Email.where(state: 0, sender_id: current_user.id).order( "created_at DESC")
    curren_company = current_user.company_id
  end

  def draft
    @emails = Email.where(state: 2, sender_id: current_user.id).order( "created_at DESC")
    curren_company = current_user.company_id
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    @user = User.find_by_email(params[:email])
    unless @user.present?
      redirect_to root_path, :danger => "Username or Password was wrong."
    else
      user_hash = BCrypt::Password.new(@user.password)
      if @user && user_hash == params[:password]
        session[:user_id] = @user.id
        if @user.is_first_login
          redirect_to "/first_sign_in"
        else
          redirect_to '/mail_box', :success => "Welcome to MailBox."
        end
      else
        redirect_to root_path, :danger => "Username or Password was wrong."
      end
    end
  end

  def save_password
    current_user.actual_password = params[:password]
    current_user.password = params[:password]
    current_user.is_first_login = false
    if current_user.save
      redirect_to '/mail_box', :success => "Welcome to MailBox."
    else
      redirect_to "/first_sign_in" , :danger => "#{current_user.errors.full_messages.first}"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def first_sign_in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)  
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase  
    "http://gravatar.com/avatar/#{gravatar_id}.png"  
  end 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserBox</title>
    <%= csrf_meta_tags %>
    <%= yield :head %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{name}" %>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/mailbox/delete.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "views/bootstrap.min" %>
  <%= stylesheet_link_tag "views/dt.boot" %>
  <%= stylesheet_link_tag "views/dashboard/select.css" %>
  <%= stylesheet_link_tag "views/dashboard/icon.css" %>
  <%= stylesheet_link_tag "views/dashboard/metisMenu.min.css" %>
  <%= stylesheet_link_tag "views/dashboard/morris.css" %>
  <%= stylesheet_link_tag "views/dashboard/style.css" %>
<% end %>

<div id="page-wrapper">

  <!-- Top Bar Start -->
  <!-- Page content start -->
  <div class="page-contentbar">

    <!--left navigation start-->
    <%= render :partial => 'shared/sidebar' %>
    <!--left navigation end-->

    <!-- START PAGE CONTENT -->
    <div id="page-right-content">
    <div class="container">
    <div class="row">
      <div class="col-sm-12">
          <div class="row">
            <div class="col-lg-12">
                <div class="m-b-20">
                  <table id="delete_datatables" class="table table-striped m-0">
                      <thead>
                        <tr role="row" class="heading">
                          <th name="order_name" class="sorting">Sender</th>
                          <th name="order_namespace" class="sorting">Message</th><th name="order_namespace" class="sorting">At</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @emails.each do |email| %>
                          <tr>
                            <td><%= email.sender.full_name %></td>
                            <td><b><%= email.subject %></b>-<font style="color:#c9c9c9"><%= email.body %></font></td>

                            <td><%= email.created_at.strftime("%I:%M %p %d-%b-%Y") %></td>
                          </tr>
                        <% end -%>
                      </tbody>
                  </table>
                </div>
              </div>
          </div>
            <!--- end row -->
        </div> <!-- end col -->
    </div> <!-- end row -->
  </div>
      <!-- end container -->

      <%= render :partial => 'shared/footer' %>
      <!-- end footer -->

    </div>
    <!-- End #page-right-content -->

  </div>
  <!-- end .page-contentbar -->
</div>

<script>
  window.current_user = <%= current_user.to_json().html_safe %>;
  $(document).ready(function () {
    window.initializeDelete();
  });
</script>

app/views/mailbox/draft.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "views/bootstrap.min" %>
  <%= stylesheet_link_tag "views/dt.boot" %>
  <%= stylesheet_link_tag "views/dashboard/select.css" %>
  <%= stylesheet_link_tag "views/dashboard/icon.css" %>
  <%= stylesheet_link_tag "views/dashboard/metisMenu.min.css" %>
  <%= stylesheet_link_tag "views/dashboard/morris.css" %>
  <%= stylesheet_link_tag "views/dashboard/style.css" %>
<% end %>

<div id="page-wrapper">

  <!-- Top Bar Start -->
  <!-- Page content start -->
  <div class="page-contentbar">

    <!--left navigation start-->
    <%= render :partial => 'shared/sidebar' %>
    
    <!--left navigation end-->

    <!-- START PAGE CONTENT -->
    <div id="page-right-content">
    <div class="container">
    <div class="row">
      <div class="col-sm-12">
          <div class="row">
            <div class="col-lg-12">
                <div class="m-b-20">
                  <table id="draft_datatables" class="table table-striped m-0">
                      <thead>
                        <tr role="row" class="heading">
                          <th name="order_name" class="sorting">Sender</th>
                          <th name="order_namespace" class="sorting">Message</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @emails.each do |email| %>
                          <tr>
                            <td><%= email.sender.full_name %></td>
                            <td><b><%= email.subject %></b>-<font style="color:#c9c9c9"><%= email.body %></font></td>
                          </tr>
                        <% end -%>
                      </tbody>
                  </table>
                </div>
              </div>
          </div>
            <!--- end row -->
        </div> <!-- end col -->
    </div> <!-- end row -->
  </div>
      <!-- end container -->

      <%= render :partial => 'shared/footer' %>
      <!-- end footer -->

    </div>
    <!-- End #page-right-content -->

  </div>
  <!-- end .page-contentbar -->
</div>

<script>
  window.current_user = <%= current_user.to_json().html_safe %>;
  $(document).ready(function () {
    window.initializeDraft();
  });
</script>

app/views/mailbox/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "views/bootstrap.min" %>
  <%= stylesheet_link_tag "views/dt.boot" %>
  <%= stylesheet_link_tag "views/dashboard/select.css" %>
  <%= stylesheet_link_tag "views/dashboard/icon.css" %>
  <%= stylesheet_link_tag "views/dashboard/metisMenu.min.css" %>
  <%= stylesheet_link_tag "views/dashboard/morris.css" %>
  <%= stylesheet_link_tag "views/dashboard/style.css" %>
<% end %>

<div id="page-wrapper">

  <!-- Top Bar Start -->
  <!-- Page content start -->
  <div class="page-contentbar">

    <!--left navigation start-->
    <%= render :partial => 'shared/sidebar' %>
    <%= render :partial => 'shared/compose_mail' %>

    <!--left navigation end-->

    <!-- START PAGE CONTENT -->
    <div id="page-right-content">
    <div class="container">
    <div class="row">
      <div class="col-sm-12">
      <div id="notification"></div>
          <h4 class="header-title"><button class="btn btn-info" id="compose-email">Compose</button></h4>
          <div class="row">
            <div class="col-lg-12">
                <div class="m-b-20">
                  <table id="emails_datatables" class="table table-striped m-0">
                      <thead>
                        <tr role="row" class="heading">
                          <th name="order_name" class="sorting">Sender</th>
                          <th name="order_namespace" class="sorting">Message</th> <th name="order_namespace" class="sorting">At</th>
                        </tr>
                      </thead>
                      <tbody id="messages-box"><div id="messages" data-company-id="<%= current_user.company_id %>">
                        <% @emails.each do |email| %>
                          <tr >

                            <td><%= email.sender.full_name %></td>
                            <td><b><%= email.subject %></b>-<font style="color:#c9c9c9">
                            <% if email.read==false %>unread
                            <% else %><b>read</b>
                            <% end %></font></td>
                            <td> <%= link_to 'Open', email_path(email) %><%= email.created_at.strftime("%I:%M%p-%d-%b-%Y") %></td>

                          </tr>
                        <% end -%>
                        </div>
                      </tbody>
                  </table>
                </div>
              </div>
          </div>
            <!--- end row -->
        </div> <!-- end col -->
    </div> <!-- end row -->
  </div>
      <!-- end container -->

      <%= render :partial => 'shared/footer' %>
      <!-- end footer -->

    </div>
    <!-- End #page-right-content -->

  </div>
  <!-- end .page-contentbar -->
</div>

<script>
  window.users = <%= @email_users.html_safe %>;
  window.current_user = <%= current_user.to_json().html_safe %>;
  $(document).ready(function () {
    window.initializeInbox();
  });
</script>

app/views/mailbox/sent.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "views/bootstrap.min" %>
  <%= stylesheet_link_tag "views/dt.boot" %>
  <%= stylesheet_link_tag "views/dashboard/select.css" %>
  <%= stylesheet_link_tag "views/dashboard/icon.css" %>
  <%= stylesheet_link_tag "views/dashboard/metisMenu.min.css" %>
  <%= stylesheet_link_tag "views/dashboard/morris.css" %>
  <%= stylesheet_link_tag "views/dashboard/style.css" %>
<% end %>

<div id="page-wrapper">

  <!-- Top Bar Start -->
  <!-- Page content start -->
  <div class="page-contentbar">

    <!--left navigation start-->
    <%= render :partial => 'shared/sidebar' %>
    <!--left navigation end-->

    <!-- START PAGE CONTENT -->
    <div id="page-right-content">
    <div class="container">
    <div class="row">
      <div class="col-sm-12">
          <div class="row">
            <div class="col-lg-12">
                <div class="m-b-20">
                  <table id="sent_datatables" class="table table-striped m-0">
                      <thead>
                        <tr role="row" class="heading">
                          <th name="order_name" class="sorting">Sender</th>
                          <th name="order_namespace" class="sorting">Message</th>   <th name="order_namespace" class="sorting">At</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @emails.each do |email| %>
                          <tr>
                            <td><%= email.recipient.full_name %></td>
                            <td><b><%= email.subject %></b>-<font style="color:#c9c9c9"><%= email.body %></font></td>
                            <td><%= email.created_at.strftime("%I:%M %p %d-%b-%Y") %></td>
                          </tr>
                        <% end -%>
                      </tbody>
                  </table>
                </div>
              </div>
          </div>
            <!--- end row -->
        </div> <!-- end col -->
    </div> <!-- end row -->
  </div>
      <!-- end container -->

      <%= render :partial => 'shared/footer' %>
      <!-- end footer -->

    </div>
    <!-- End #page-right-content -->

  </div>
  <!-- end .page-contentbar -->
</div>

<script>
  window.current_user = <%= current_user.to_json().html_safe %>;
  $(document).ready(function () {
    window.initializeSent();
  });
</script>

app/views/shared/_compose_mail.html.erb
<div id="modal-add-email" class="modal fade" data-backdrop="static" data-keyboard="false">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center" style="width:45%;">
      <div class="modal-content">
<!--         <div class="modal-header">
          <div class="caption"><h2>Add Company Details</h2></div>
        </div> -->
        <div class="modal-body">
          <div class="alert alert-danger alert-dismissible fade in hidden error-on-save" role="alert">
              <strong>Oh snap!</strong> <p id="error-reason"></p>
          </div>
            <button id="closebutton" type="button" class="close" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          <div class="container">

          
              <div class="content-container clearfix">
                  <div class="col-md-12">
                      <div class="form-group">
                        <select id="all-to-email" multiple="multiple" name="all-user-email" class="js-example-tags form-control" style="width: 476px">
                        </select>
                      </div>
                      <div class="form-group">
                        <select id="all-cc-email" multiple="multiple" name="all-user-email" class="js-example-tags form-control" style="width: 476px">
                        </select>
                      </div>
                      <div class="form-group">
                        <select id="all-bcc-email" multiple="multiple" name="all-user-email" class="js-example-tags form-control" style="width: 476px">
                        </select>
                      </div>
                      <div class="form-group">
                          <input id="email-subject" type="text" class="form-control" placeholder="Subject" />
                      </div>
                      <textarea id="email-text" class="form-control" placeholder="message"></textarea>
                      <span class="btn btn-default btn-file">
                              Browse <input id="email-attach"  class="form-control" placeholder="attach" type="file">
                      </span>
                  </div>
              </div>
          </div>
        </div>
        <fieldset>
          <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn btn-info pull-right marging-left" id="save-draft">Draft</button>
            <button type="button"  class="btn btn-success pull-left" id="send-email">Send</button>
          </div>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/shared/_email.html.erb
    <div class="alert alert-warning" role="alert">
    New mail from
   <%= email.sender.full_name %>
    <b><%= email.subject %></b>-<font style="color:#c9c9c9"><%= email.body %></font>
<button id="closebutton" type="button" class="close" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>

</div>

app/views/shared/_farword.html.erb
<div id="modal-farword-email" class="modal fade" data-backdrop="static" data-keyboard="false">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center" style="width:45%;">
      <div class="modal-content">
<!--         <div class="modal-header">
          <div class="caption"><h2>Add Company Details</h2></div>
        </div> -->
        <div class="modal-body">
          <div class="alert alert-danger alert-dismissible fade in hidden error-on-save" role="alert">
              <strong>Oh snap!</strong> <p id="error-reason"></p>
          </div>
            <button id="closefarbutton" type="button" class="close" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          <div class="container">

          
              <div class="content-container clearfix">
                  <div class="col-md-12">
                      <div class="form-group">
                        <select id="all-to-email" multiple="multiple" name="all-user-email" class="js-example-tags form-control" >
                        </select>
                      </div>
                      <div class="form-group">
                          <input id="email-subject" type="text" class="form-control" placeholder="Subject" />
                      </div>
                  
                      <textarea id="email-texti" class="form-control" placeholder="message"></textarea>
                     
                  </div>
              </div>
          </div>
        </div>
        <fieldset>
          <div class="modal-footer">
            <button type="button"  class="btn btn-success pull-left" id="farword-email">Send</button>
          </div>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
      <div class="footer">
        <div class="pull-right hidden-xs">
           <strong class="text-custom">Email intranet</strong>.
        </div>
        <div>
          <strong>Simple Admin</strong> - Copyright © 2017
        </div>
      </div>

app/views/shared/_mainbar.html.erb
<div id="main-bar">
  <p class="title-empty"></p>
  <div class="area-for-dt">
    <table id="users_datatables" class="table table-striped m-0">
        <thead>
            <tr role="row" class="heading">
                <th name="order_id" class="sorting">#</th>
                <th name="order_fullname" class="sorting">Fullname</th>
            </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th scope='row'><%= user.id %></th>
              <td><%= user.full_name %></td>
            </tr>
          <% end -%>
        </tbody>
    </table>
  </div>
</div>

<script>
  $(document).ready(function () {
    window.initializeMainBar();
  });
</script>

app/views/shared/_notification.html.erb
 <tr >

                            <td><%= email.sender.full_name %></td>
                            <td><b><%= email.subject %></b>-<font style="color:#c9c9c9">
                            <% if email.read==false %>unread
                            <% else %><b>read</b>
                            <% end %></font></td>
                            <td> <%= link_to 'Open', email_path(email) %><%= email.created_at.strftime("%I:%M%p-%d-%b-%Y") %></td>

                          </tr>

app/views/shared/_reply.html.erb
<div id="modal-reply-email" class="modal fade" data-backdrop="static" data-keyboard="false">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center" style="width:45%;">
      <div class="modal-content">
<!--         <div class="modal-header">
          <div class="caption"><h2>Add Company Details</h2></div>
        </div> -->
        <div class="modal-body">
          <div class="alert alert-danger alert-dismissible fade in hidden error-on-save" role="alert">
              <strong>Oh snap!</strong> <p id="error-reason"></p>
          </div>
            <button id="closereplybutton" type="button" class="close" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          <div class="container">

          
              <div class="content-container clearfix">
                  <div class="col-md-12">
                      
                  
                      <textarea id="email-text" class="form-control" placeholder="message"></textarea>
                     
                  </div>
              </div>
          </div>
        </div>
        <fieldset>
          <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn btn-info pull-right marging-left" id="save-draft">Draft</button>
            <button type="button"  class="btn btn-success pull-left" id="reply-email">Send</button>
          </div>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<aside class="sidebar-navigation">
      <div class="scrollbar-wrapper">
        <div>
          <button type="button" class="button-menu-mobile btn-mobile-view visible-xs visible-sm">
            <i class="mdi mdi-close"></i>
          </button>
          <!-- User Detail box -->
          <div class="user-details active">
            <div class="pull-left">
              <img src="<%= avatar_url(current_user) %>" alt="" class="thumb-md img-circle">
            </div>
            <div class="user-info">
              <a href="#" id="current" data-current-user="<%= current_user.id %>" ><%= current_user.full_name %></a>
              <p class="text-muted m-0"><div id="company_id"> <%= current_user.company_id %></div></p>
            </div>
          </div>
          <!--- End User Detail box -->

          <!-- Left Menu Start -->
          <ul class="metisMenu nav" id="side-menu">
            <li>
              <a href="/mail_box" class="active"><i class="fa fa-inbox"></i><b>Inbox</b></a>
            </li>
            <li>
              <a href="/mail_box_sent" class="active"><i class="fa fa-paper-plane"></i><b>Sent</b></a>
            </li>
            <li>
              <a href="/mail_box_draft" class="active"><i class="fa fa-floppy-o"></i><b>Draft</b></a>
            </li>
            <li>
              <a href="/mail_box_delete" class="active"><i class="fa fa-trash"></i><b>Delete</b></a>
            </li>
          </ul>
        </div>
      </div>
      <!--Scrollbar wrapper-->
    </aside>

app/views/utils/_inbox.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "views/bootstrap.min" %>
  <%= stylesheet_link_tag "views/dashboard/icon.css" %>
  <%= stylesheet_link_tag "views/dashboard/metisMenu.min.css" %>
  <%= stylesheet_link_tag "views/dashboard/morris.css" %>
  <%= stylesheet_link_tag "views/dashboard/style.css" %>
<% end %>

<div id="page-wrapper">

  <!-- Top Bar Start -->
  <!-- Page content start -->
  <div class="page-contentbar">

    <!--left navigation start-->
    <%= render :partial => 'shared/sidebar' %>
    <%= render :partial => 'shared/add_email' %>
    <!--left navigation end-->

    <!-- START PAGE CONTENT -->
    <div id="page-right-content">
    <div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h4 class="header-title">Inbox</h4>
            <div class="row">
                <div class="col-lg-12">
                    <div class="m-b-20">
                        <table id="emails_datatables" class="table table-striped m-0">
                            <thead>
                                <tr role="row" class="heading">
                                    <th name="order_id" class="sorting">#</th>
                                    <th name="order_name" class="sorting">email Name</th>
                                    <th name="order_namespace" class="sorting">Namespace</th>
                                    <th name="order_name" class="sorting">Owner Name</th>
                                    <th name="order_created_at" class="sorting">Created At</th>
                                </tr>
                            </thead>
                            <tbody>
                              <% @emails.each do |email| %>
                                <tr>
                                  <th scope='row'><%= email.id %></th>
                                  <td><%= email.subject %></td>
                                  <td><%= email.body %></td>
                                  <td><%= email.sender.full_name %></td>
                                  <td><%= email.reciever.full_name %></td>
                                </tr>
                              <% end -%>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            <!--- end row -->
        </div> <!-- end col -->
    </div> <!-- end row -->
  </div>
      <!-- end container -->

      <%= render :partial => 'shared/footer' %>
      <!-- end footer -->

    </div>
    <!-- End #page-right-content -->

  </div>
  <!-- end .page-contentbar -->
</div>

<script>
  $(document).ready(function () {
    window.initializeInbox();
  });
</script>

app/views/welcome/first_sign_in.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "views/welcome/first_sign_in.css" %>
  <%= stylesheet_link_tag "views/welcome/welcome.min.css" %>
<% end %>
<section id="overload">
  <div class="row">
    <div class="alert alert-dismissible alert-success">
      <strong>Well done!</strong> You successfully signed in. As this was your first login please reset your password.
    </div>
    <div class="col-lg-4" style="float: none; margin: 0 auto;">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= current_user.full_name %></h3>
        </div>
        <div class="panel-body">
          <form action="/save_password" method="POST" accept-charset="utf-8">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <div class="form-group has-success">
              <label class="control-label" for="inputSuccess">Password</label>
              <input type="password" class="form-control" id="inputSuccess" name="password">
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-info">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>